module.exports = {
  disableEmoji: false,
  format: '[{scope}@{type}]: {subject}',
  list: [
    'asset',
    'feat',
    'fix',
    'docs',
    'style',
    'refactor',
    'test',
    'chore',
    'config',
    'rename',
    'ci',
    'perf',
    'type',
    'init',
    'delete',
    'api',
  ],
  maxMessageLength: 64,
  minMessageLength: 3,
  questions: ['type', 'scope', 'subject'],
  scopes: ['blog'],
  types: {
    init: {
      description: 'Initialize a new project or module',
      emoji: '🎉',
      value: 'init',
    },
    api: {
      description: 'Changes related to API integration or updates',
      emoji: '🔌',
      value: 'api',
    },
    feat: {
      description: 'Add a new feature',
      emoji: '🎸',
      value: 'feat',
    },
    fix: {
      description: 'Fix a bug or issue',
      emoji: '🐛',
      value: 'fix',
    },
    docs: {
      description: 'Add or update documentation',
      emoji: '✏️ ',
      value: 'docs',
    },
    style: {
      description: 'Add or update styles and UI components',
      emoji: '💄',
      value: 'style',
    },
    refactor: {
      description: 'Refactor code without changing its behavior',
      emoji: '💡',
      value: 'refactor',
    },
    test: {
      description: 'Code change related with tests cases',
      emoji: '💍',
      value: 'test',
    },
    chore: {
      description: 'Changes to the build process or auxiliary tools and libraries such as documentation generation',
      emoji: '🤖',
      value: 'chore',
    },
    config: {
      description: 'Changes to configuration files or settings',
      emoji: '🔧',
      value: 'config',
    },
    rename: {
      description: 'Rename files or directories without changing the code',
      emoji: '🔄',
      value: 'rename',
    },
    ci: {
      description: 'CI related changes',
      emoji: '🎡',
      value: 'ci',
    },
    perf: {
      description: 'A code change that improves performance',
      emoji: '⚡️',
      value: 'perf',
    },
    type: {
      description: 'add or update type',
      emoji: '🏷️',
      value: 'type',
    },
    asset: {
      description: 'Add or update static assets (images, fonts, etc.)',
      emoji: '📦',
      value: 'asset',
    },
    delete: {
      description: 'Remove files or code',
      emoji: '🗑️',
      value: 'delete',
    },
    messages: {
      type: "Select the type of change that you're committing:",
      customScope: 'Select the scope this component affects:',
      subject: 'Write a short, imperative mood description of the change:\n',
      body: 'Provide a longer description of the change:\n ',
      breaking: 'List any breaking changes:\n',
      footer: 'Issues this commit closes, e.g #123:',
      confirmCommit: 'The packages that this commit has affected\n',
    },
  },
};
